Cleanup, remove unused python code

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -74,8 +74,19 @@ if [ ! -d jena-fuseki ]; then
     fi
 fi
 
-# bin/setup/python
-# npm install
+npm install
+
+if [ ! -f node_modules/n3/browser/n3-browser.js ]; then
+    cd node_modules/n3
+    npm install
+    browser/build-browser-versions
+    cd "$PROJECT_ROOT"
+fi
+
+if [ ! -f node_modules/n3/browser/n3-browser.js ]; then
+    echo "ERROR: failed build N3 browser version"
+    exit 1
+fi
 
 echo "========================================================"
 echo " Setup is complete. "
